<?php

acf_add_local_field_group(array(
	'key' => 'group_5f3fc944d99f1',
	'title' => __("Page Content", 'ultimate-auction-pro-software'),
	'fields' => array(
		array(
			'key' => 'field_5f3fc98b06bce',
			'label' => __("Add	Layout", 'ultimate-auction-pro-software'),
			'name' => 'uat_flex_content_mgt',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5f3fc9968fc32' => array(
					'key' => 'layout_5f3fc9968fc32',
					'name' => 'uat_content_banner_slider',
					'label' => __("Banner Slider", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f436a8254c7a',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_banner_slider_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f436b9de83c1',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_banner_slider_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f3fc9ea06bcf',
							'label' => __("Add Slider", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_banner_slider',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => __("Add	New Slide", 'ultimate-auction-pro-software'),
							'sub_fields' => array(
								array(
									'key' => 'field_5f5f69c0e1ef8',
									'label' => __("Text", 'ultimate-auction-pro-software'),
									'name' => 'uat_content_banner_left_text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5f3fca2106bd0',
									'label' => __("Add Left Slide", 'ultimate-auction-pro-software'),
									'name' => 'uat_content_banner_left',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5f3fca4e06bd1',
									'label' => __("Button Link", 'ultimate-auction-pro-software'),
									'name' => 'button_link',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
								array(
									'key' => 'field_5f5f6990e1ef7',
									'label' => __("Text", 'ultimate-auction-pro-software'),
									'name' => 'uat_content_banner_right_text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5f478d0849ed1',
									'label' => __("Add Right Slide", 'ultimate-auction-pro-software'),
									'name' => 'uat_content_banner_right',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5f478d2049ed2',
									'label' => __("Button Link", 'ultimate-auction-pro-software'),
									'name' => 'button_link_right',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f48ab41b5893' => array(
					'key' => 'layout_5f48ab41b5893',
					'name' => 'uat_content_auction_product_slider',
					'label' => __("Auction Product Slider", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f48ab41b5894',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_auction_product_slider_section_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f48ab41b5895',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_auction_product_slider_section_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f48ab41b5896',
							'label' => __("Auction Product Slider", 'ultimate-auction-pro-software'),
							'name' => 'uat_auction_product_slider',
							'type' => 'repeater',
							'instructions' => __("Please select all the auction products that you want to display in this section.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => __("Add Slide", 'ultimate-auction-pro-software'),
							'sub_fields' => array(
								array(
									'key' => 'field_5f48ab41b5897',
									'label' => __("Select Left Auction Product", 'ultimate-auction-pro-software'),
									'name' => 'select_auction_product',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array(
										0 => 'product',
									),
									'taxonomy' => array(
										0 => 'product_type:auction',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'ui' => 1,
								),
								array(
									'key' => 'field_5f48ab41b5898',
									'label' => __("Button Link", 'ultimate-auction-pro-software'),
									'name' => 'button_link',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
								array(
									'key' => 'field_5f48ab41b5899',
									'label' => __("Select Right Auction Product", 'ultimate-auction-pro-software'),
									'name' => 'select_auction_product_right',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array(
										0 => 'product',
									),
									'taxonomy' => array(
										0 => 'product_type:auction',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'ui' => 1,
								),
								array(
									'key' => 'field_5f48ab41b589a',
									'label' => __("Button Link", 'ultimate-auction-pro-software'),
									'name' => 'button_link_right',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f6361d02e293' => array(
					'key' => 'layout_5f6361d02e293',
					'name' => 'uat_content_featured_categories',
					'label' => __("Featured Categories", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f6361d02e294',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_featured_categories_section_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f6361d02e295',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_featured_categories_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f63620a2e29b',
							'label' => __("Select Auction Product Categories", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_featured_categories_list',
							'type' => 'taxonomy',
							'instructions' => __("Select Auction Product Categories.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'product_cat',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f3fcaf1c6b29' => array(
					'key' => 'layout_5f3fcaf1c6b29',
					'name' => 'uat_content_active_bid',
					'label' => __("Active Bid", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f436ea66aa94',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_active_bid_section_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f436ec46aa95',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_active_bid_section_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f3fd19b3895a',
							'label' => __("How many active bids do you want to display?", 'ultimate-auction-pro-software'),
							'name' => 'uat_active_bid_section_no',
							'type' => 'number',
							'instructions' => __("This will display the active bids of the auction products. This will show the number of auction products to display in this section. Default is 10.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '10',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'uat_active_bid_section_timer',
							'label' => __("Timer", 'ultimate-auction-pro-software'),
							'name' => 'uat_active_bid_section_timer',
							'type' => 'button_group',
							'instructions' => __("Display countdown clock.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => 'uat_button_group',
								'id' => '',
							),
							'choices' => array(
								'true' => __("ON", 'ultimate-auction-pro-software'),
								'false' => __("OFF", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'false',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f3fcf8335c3e' => array(
					'key' => 'layout_5f3fcf8335c3e',
					'name' => 'uat_content_current_upcoming_auctions',
					'label' => __("Live & Future Events", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f4370120cf32',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_current_upcoming_auctions_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f436fef0cf31',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_current_upcoming_auctions_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => '',
						),
						array(
							'key' => 'field_5f3fd06007b4c',
							'label' => __("How many live events do you want to display ?", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_current_upcoming_auctions_no',
							'type' => 'number',
							'instructions' => __("Add Number of\"live auction events to display in this section.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '10',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f48f793b20be',
							'label' => __("How many future events do you want to display?", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_upcoming_auctions_no',
							'type' => 'number',
							'instructions' => __("Add Number of future auction events to display in this section.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '10',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'uat_content_upcoming_auctions_timer',
							'label' => __("Timer", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_upcoming_auctions_timer',
							'type' => 'button_group',
							'instructions' => __("Display countdown clock.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => 'uat_button_group',
								'id' => '',
							),
							'choices' => array(
								'true' => __("ON", 'ultimate-auction-pro-software'),
								'false' => __("OFF", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'false',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),

					),
					'min' => '',
					'max' => '',
				),
				'layout_5f48ed9fa0464' => array(
					'key' => 'layout_5f48ed9fa0464',
					'name' => 'uat_content_live_auction_events',
					'label' => __("Live Auction Events", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f48ed9fa0465',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_live_auction_events_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f48ed9fa0466',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_live_auction_events_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f48ed9fa0467',
							'label' => __("How many events do you want to display ?", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_live_auction_events_no',
							'type' => 'number',
							'instructions' => __("Add Number of auction events to display in this section. Default is 10.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'uat_content_live_auction_events_timer',
							'label' => __("Timer", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_live_auction_events_timer',
							'type' => 'button_group',
							'instructions' => __("Display countdown clock.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => 'uat_button_group',
								'id' => '',
							),
							'choices' => array(
								'true' => __("ON", 'ultimate-auction-pro-software'),
								'false' => __("OFF", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'true',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f4509b6cc6b2' => array(
					'key' => 'layout_5f4509b6cc6b2',
					'name' => 'uat_content_future_auction_events',
					'label' => __("Future Auction Events", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f4509b6cc6b3',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_future_auction_events_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f4509b7cc6b5',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_future_auction_events_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f4509b6cc6b4',
							'label' => __("How many events do you want to display ?", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_future_auction_events_no',
							'type' => 'number',
							'instructions' => __("Add Number of auction events to display in this section. Default is 10.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '10',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'uat_content_future_auction_events_timer',
							'label' => __("Timer", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_future_auction_events_timer',
							'type' => 'button_group',
							'instructions' => __("Display countdown clock.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => 'uat_button_group',
								'id' => '',
							),
							'choices' => array(
								'true' => __("ON", 'ultimate-auction-pro-software'),
								'false' => __("OFF", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'false',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f4372dd9679b' => array(
					'key' => 'layout_5f4372dd9679b',
					'name' => 'uat_content_past_auction_events',
					'label' => __("Past Auction Events", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f4372dd9679c',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_past_auction_events_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f4372dd9679e',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_past_auction_events_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f4372dd9679d',
							'label' => __("How many events do you want to display ?", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_past_auction_events_no',
							'type' => 'number',
							'instructions' => __("Add Number of Events to display in this section. Default is 10.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '10',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f3fd1e724a72' => array(
					'key' => 'layout_5f3fd1e724a72',
					'name' => 'uat_content_trending_items',
					'label' => __("Trending Auction Products", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f436fe50cf30',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_trending_items_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f4370340cf34',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_trending_items_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f3fd21624a75',
							'label' => __("Select Trending Product Type", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_trending_items_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'most_view' => __("Show products with most views", 'ultimate-auction-pro-software'),
								'most_bid' => __("Show products with most bids", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 'most_bid',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f48a71afe9d3',
							'label' => __("How many items do you want to display?", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_trending_items_no',
							'type' => 'number',
							'instructions' => __("Add Number of items to display in this section. Default is 10.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '10',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'uat_content_trending_items_timer',
							'label' => __("Timer", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_trending_items_timer',
							'type' => 'button_group',
							'instructions' => __("Display countdown clock.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => 'uat_button_group',
								'id' => '',
							),
							'choices' => array(
								'true' => __("ON", 'ultimate-auction-pro-software'),
								'false' => __("OFF", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'true',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f3fd315eb114' => array(
					'key' => 'layout_5f3fd315eb114',
					'name' => 'uat_content_blog_post',
					'label' => __("Media (Blog)", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f4371902c020',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_blog_post_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f4371992c021',
							'label' => __("Add Section Link", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_blog_post_link',
							'type' => 'link',
							'instructions' => __("Add section link here like : view all", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f45110f49c2b',
							'label' => __("Select Media (Blog) Type", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_blog_post_type',
							'type' => 'button_group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'latest_media' => __("Show latest media(blog)", 'ultimate-auction-pro-software'),
								'manually_media' => __("Select manually media(blog)", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'latest_media',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_5f45121287db1',
							'label' => __("Select Left Media (Blog).", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_blog_post_type_manually',
							'type' => 'post_object',
							'instructions' => __("Please select blogs to display in left side.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f45110f49c2b',
										'operator' => '==',
										'value' => 'manually_media',
									),
								),
							),
							'wrapper' => array(
								'width' => '35',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'post',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5f466f8d99d6b',
							'label' => __("Select Right Media (Blog)", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_blog_post_type_manually_right',
							'type' => 'post_object',
							'instructions' => __("Please select rhe blog post to display in the right side section. Maximum is 4.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f45110f49c2b',
										'operator' => '==',
										'value' => 'manually_media',
									),
								),
							),
							'wrapper' => array(
								'width' => '65',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'post',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 1,
							'return_format' => 'object',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),

				'layout_6149d34791437' => array(
					'key' => 'layout_6149d34791437',
					'name' => 'uat_heading',
					'label' => __("Heading ", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6149d37f97686',
							'label' => __("Heading", 'ultimate-auction-pro-software'),
							'name' => 'uat_heading_title',
							'type' => 'text',
							'instructions' =>"",
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6149d626734cb' => array(
					'key' => 'layout_6149d626734cb',
					'name' => 'uat_full_width_content',
					'label' => __("Full Width Content", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
					    array(
							'key' => 'uat_full_width_content_title',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_full_width_content_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_6149d626734cc',
							'label' => __("Content", 'ultimate-auction-pro-software'),
							'name' => 'uat_full_width_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6149d3f8d7880' => array(
					'key' => 'layout_6149d3f8d7880',
					'name' => 'uat_two_column',
					'label' => __("2 Column", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'uat_two_column_title',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_two_column_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_6149d3f8d7881',
							'label' => __("Column 1 Content", 'ultimate-auction-pro-software'),
							'name' => 'two_col_content_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_6149d405d7882',
							'label' => __("Column 2 Content", 'ultimate-auction-pro-software'),
							'name' => 'two_col_content_2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_uat_three_column' => array(
					'key' => 'layout_uat_three_column',
					'name' => 'uat_three_column',
					'label' => __("3 Column", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'uat_three_column_title',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_three_column_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'three_col_content_1',
							'label' => __("Column 1 Content", 'ultimate-auction-pro-software'),
							'name' => 'three_col_content_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'three_col_content_2',
							'label' => __("Column 2 Content", 'ultimate-auction-pro-software'),
							'name' => 'three_col_content_2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'three_col_content_3',
							'label' => __("Column 3 Content", 'ultimate-auction-pro-software'),
							'name' => 'three_col_content_3',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_uat_four_column' => array(
					'key' => 'layout_uat_four_column',
					'name' => 'uat_four_column',
					'label' => __("4 Column", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'uat_four_column_title',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_four_column_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'four_col_content_1',
							'label' => __("Column 1 Content", 'ultimate-auction-pro-software'),
							'name' => 'four_col_content_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'four_col_content_2',
							'label' => __("Column 2 Content", 'ultimate-auction-pro-software'),
							'name' => 'four_col_content_2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'four_col_content_3',
							'label' => __("Column 3 Content", 'ultimate-auction-pro-software'),
							'name' => 'four_col_content_3',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'four_col_content_4',
							'label' => __("Column 4 Content", 'ultimate-auction-pro-software'),
							'name' => 'four_col_content_4',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6149d545e6b25' => array(
					'key' => 'layout_6149d545e6b25',
					'name' => 'uat_full_width_image',
					'label' => __("Full Width Image ", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6149d9554f4df',
							'label' => __("Display Inside Container?", 'ultimate-auction-pro-software'),
							'name' => 'uat_full_width_image_container',
							'type' => 'button_group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'yes' => __("Yes", 'ultimate-auction-pro-software'),
								'no' => __("No", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'yes',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_6149d545e6b26',
							'label' => __("Upload Image", 'ultimate-auction-pro-software'),
							'name' => 'uat_full_width_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6149d6b699b4c' => array(
					'key' => 'layout_6149d6b699b4c',
					'name' => 'uat_right_image_left_content',
					'label' => __("Right Image Left Content", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
					    array(
							'key' => 'uat_right_image_left_content_title',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_right_image_left_content_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_6149d6b699b4d',
							'label' => __("Content", 'ultimate-auction-pro-software'),
							'name' => 'uat_right_image_left_content_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_6149d6dd99b4e',
							'label' => __("Image", 'ultimate-auction-pro-software'),
							'name' => 'uat_right_image_left_content_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6149d723ffa3a' => array(
					'key' => 'layout_6149d723ffa3a',
					'name' => 'uat_left_image_right_content',
					'label' => __("Left Image Right Content", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'uat_left_image_right_content_title',
							'label' => __("Section Title", 'ultimate-auction-pro-software'),
							'name' => 'uat_left_image_right_content_title',
							'type' => 'text',
							'instructions' => __("Add section title here.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_6149d723ffa3c',
							'label' => __("Image", 'ultimate-auction-pro-software'),
							'name' => 'uat_left_image_right_content_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_6149d723ffa3b',
							'label' => __("Content", 'ultimate-auction-pro-software'),
							'name' => 'uat_left_image_right_content_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),

				'layout_5f43b01359f4a' => array(
					'key' => 'layout_5f43b01359f4a',
					'name' => 'uat_content_border_line',
					'label' => __("Horizontal Line", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f43b0ae64249',
							'label' => __("Display Border Line", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_display_border_line',
							'type' => 'button_group',
							'instructions' => __("This will draw horizontal line.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'yes' => __("Yes", 'ultimate-auction-pro-software'),
								'no' => __("No", 'ultimate-auction-pro-software'),
							),
							'allow_null' => 0,
							'default_value' => 'yes',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f43b11cea446' => array(
					'key' => 'layout_5f43b11cea446',
					'name' => 'uat_content_empty_space',
					'label' => __("Empty Space", 'ultimate-auction-pro-software'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f43b11cea447',
							'label' => __("Add Empty Space In pixels", 'ultimate-auction-pro-software'),
							'name' => 'uat_content_spacer_pixel',
							'type' => 'number',
							'instructions' => __("Write in number Ex. 10, 20 ,30 etc.In Mobile Device it will becomes half of the entered value. Default is 10px.", 'ultimate-auction-pro-software'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '10',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 1,
							'max' => '',
							'step' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => __("Add Section", 'ultimate-auction-pro-software'),
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/template-full-width.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/template-left-sidebar.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/template-right-sidebar.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/template-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));