<?php 
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_653c9b7a0b217',
	'title' => 'Seller Product Details',
	'fields' => array(
		array(
			'key' => 'field_653922f41749a',
			'label' => 'Seller Details',
			'name' => '',
			'aria-label' => '',
			'type' => 'page',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => true,
			'show_numbering' => 0,
			'previous_text' => '',
			'next_text' => '',
		),
		array(
			'key' => 'field_6482c59cccfe4',
			'label' => 'Dealer or private party?',
			'name' => 'details_public_or_privet',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'choices' => array(
				'dealer' => 'Dealer',
				'private_party' => 'Private party',
			),
			'default_value' => 'dealer',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_648008c9ca46b',
			'label' => 'First Name',
			'name' => 'auction_seller_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'First Name',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64800913ca46c',
			'label' => 'Last Name',
			'name' => 'auction_seller_l_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Last Name',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64800923ca46d',
			'label' => 'Email Address',
			'name' => 'email_address',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'placeholder' => 'Email Address',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64800950ca46e',
			'label' => 'Contact phone Number',
			'name' => 'contact_phone_number',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Contact phone Number',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6480099cca46f',
			'label' => 'Address',
			'name' => 'contact_details',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'rows' => 5,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_64833d91183fa',
			'label' => 'Company Logo',
			'name' => 'auction_company_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6482c59cccfe4',
						'operator' => '==',
						'value' => 'dealer',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_648342b3fec92',
			'label' => 'Dealer Notes',
			'name' => 'cmf_dealer_notes',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'rows' => 5,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6539239adbda2',
			'label' => 'Vehicle Specification',
			'name' => '',
			'aria-label' => '',
			'type' => 'page',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => true,
			'show_numbering' => 0,
			'previous_text' => '',
			'next_text' => '',
		),
		array(
			'key' => 'field_64833de1183fb',
			'label' => 'Specification Summary',
			'name' => 'cmf_specification',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_64833def183fc',
			'label' => 'Year',
			'name' => 'cmf_year',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'min' => 4,
			'max' => '',
			'placeholder' => 'Year',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833f3cc3d9b',
			'label' => 'Title Status',
			'name' => 'cmf_title_status',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Title Status',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833e1e183fd',
			'label' => 'Make',
			'name' => 'cmf_make',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'taxonomy' => 'car_models',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 1,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_64833e2e183fe',
			'label' => 'Model',
			'name' => 'cmf_model',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'taxonomy' => 'car_models',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 1,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
			'choices' => array(
				'Audi' => array(
				),
				100 => '100',
				200 => '200',
				80 => '80',
				'A1' => 'A1',
				'A2' => 'A2',
				'A3' => 'A3',
				'A4' => 'A4',
				'A5' => 'A5',
				'A6' => 'A6',
				'A7' => 'A7',
				'A8' => 'A8',
				'QUATTRO' => 'QUATTRO',
				'S1' => 'S1',
				'S2' => 'S2',
				'S3' => 'S3',
				'S4' => array(
				),
				'S5' => array(
				),
				'S6' => 'S6',
				'S7' => 'S7',
				'S8' => 'S8',
				'Austin' => array(
				),
				'Healey MK I' => 'Healey MK I',
				'Healey MK II' => 'Healey MK II',
				'Healey MK III' => 'Healey MK III',
				'BMW' => array(
				),
				'1-serie' => '1-serie',
				'1M' => '1M',
				'2-serie' => '2-serie',
				'3-serie' => '3-serie',
				'4-serie' => '4-serie',
				'5-serie' => '5-serie',
				'6-serie' => '6-serie',
				'8-serie' => '8-serie',
				'M2' => 'M2',
				'M3' => 'M3',
				'M4' => 'M4',
				'M550i' => 'M550i',
				'X1' => 'X1',
				'X2' => 'X2',
				'X3' => 'X3',
				'X5' => 'X5',
				'X6' => 'X6',
				'Buick' => array(
				),
				'Century Caballer' => 'Century Caballer',
				'Roadmaster' => 'Roadmaster',
				'Cadillac' => array(
				),
				'ELDORADO' => 'ELDORADO',
				'Fleetwood 75' => 'Fleetwood 75',
				'Chevrolet' => array(
				),
				'C10 Shortbed Stepside Pickup' => 'C10 Shortbed Stepside Pickup',
				'Corvette C3 Stingray' => 'Corvette C3 Stingray',
				'Short Stepside' => 'Short Stepside',
				'Chrysler' => array(
				),
				'WINDSOR' => 'WINDSOR',
				'Datsun' => array(
				),
				'240z' => '240z',
				'280z' => '280z',
				'Ferrari' => array(
				),
				'812 GTS' => '812 GTS',
				'812 Superfast' => '812 Superfast',
				'Testarossa' => 'Testarossa',
				'Fiat' => array(
				),
				128 => '128',
				'Fisker' => array(
				),
				'Karma ecoChic' => 'Karma ecoChic',
				'Ford' => array(
				),
				'Escort' => 'Escort',
				'Super Deluxe Tudor' => 'Super Deluxe Tudor',
				'GMC' => array(
				),
				'Typhoon' => 'Typhoon',
				'Land Rover' => array(
				),
				'101 FC' => '101 FC',
				'Mazda' => array(
				),
				323 => '323',
				626 => '626',
				929 => '929',
				'Mercedes' => array(
				),
				'R129' => 'R129',
				'W107' => 'W107',
				'W115' => 'W115',
				'W123' => 'W123',
				'W124' => 'W124',
				'W202' => 'W202',
				'Mini' => array(
				),
				'Mini Cooper' => 'Mini Cooper',
				'Mini Cooper Clubman' => 'Mini Cooper Clubman',
				'Mini Cooper S' => 'Mini Cooper S',
				'Mini Cooper S WORKS' => 'Mini Cooper S WORKS',
				'Mini One' => 'Mini One',
				'Opel' => array(
				),
				'Speedster' => 'Speedster',
				'Porsche' => array(
				),
				356 => '356',
				718 => '718',
				911 => '911',
				912 => '912',
				914 => '914',
				'914-6' => '914-6',
				'918 spyder' => '918 spyder',
				924 => '924',
				928 => '928',
				930 => '930',
				944 => '944',
				959 => '959',
				968 => '968',
				'Boxster' => 'Boxster',
				'Cayenne' => 'Cayenne',
				'Cayman' => 'Cayman',
				'GT3' => 'GT3',
				'Macan' => 'Macan',
				'Panamera' => 'Panamera',
				'Toyota' => array(
				),
				'Celica' => 'Celica',
				'Land Cruiser' => 'Land Cruiser',
				'Triumph' => array(
				),
				'Burlington Arrow' => 'Burlington Arrow',
				'Herald Burlington' => 'Herald Burlington',
				'Volkswagen' => array(
				),
				'Bobbel' => 'Bobbel',
				'Golf MK1' => 'Golf MK1',
				'T1 Type2' => 'T1 Type2',
				'Zimmer' => array(
				),
				'Golden Spirit' => 'Golden Spirit',
			),
		),
		array(
			'key' => 'field_64833ee4c3d96',
			'label' => 'Engine',
			'name' => 'cmf_engine',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Engine',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a195267a1b',
			'label' => 'Engine size',
			'name' => 'cmf_engine_size',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Engine size',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833eb6c3d94',
			'label' => 'Mileage',
			'name' => 'cmf_mileage',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => 0,
			'min' => '',
			'max' => '',
			'placeholder' => 'Mileage',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_648341a17a01e',
			'label' => 'Mileage Reported',
			'name' => 'cmf_mileage_reported',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Mileage Reported',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a1a9067a23',
			'label' => 'Kilometers',
			'name' => 'cmf_kilometers',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Mileage Reported',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833ea1c3d93',
			'label' => 'VIN',
			'name' => 'cmf_vin',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'VIN',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'cmf_condition',
			'label' => 'Condition',
			'name' => 'cmf_condition',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Condition',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a194167a1a',
			'label' => 'Horsepower',
			'name' => 'cmf_horsepower',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Horsepower',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833ed5c3d95',
			'label' => 'Body Style',
			'name' => 'cmf_body_style',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Body Style',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833efbc3d97',
			'label' => 'Drivetrain',
			'name' => 'cmf_drivetrain',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Drivetrain',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833f07c3d98',
			'label' => 'Transmission',
			'name' => 'cmf_transmission',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Transmission',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833f19c3d99',
			'label' => 'Exterior Color',
			'name' => 'cmf_exterior_color',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Exterior Color',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64833f29c3d9a',
			'label' => 'Interior Color',
			'name' => 'cmf_interior_color',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Interior Color',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_648340db7a015',
			'label' => 'Registration date',
			'name' => 'cmf_registration_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_648341007a016',
			'label' => 'Drive Type',
			'name' => 'cmf_drive_type',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Drive Type',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6483410d7a017',
			'label' => 'Cylinders',
			'name' => 'cmf_cylinders',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Cylinders',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6483411c7a018',
			'label' => 'Doors',
			'name' => 'cmf_doors',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Doors',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6483412a7a019',
			'label' => 'Fuel type',
			'name' => 'cmf_fuel_type',
			'aria-label' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'choices' => array(
				'Gasoline' => 'Gasoline',
				'Diesel' => 'Diesel',
				'Hybrid' => 'Hybrid',
				'Electric' => 'Electric',
				'Patrol' => 'Petrol',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'allow_custom' => 0,
			'layout' => 'horizontal',
			'toggle' => 0,
			'save_custom' => 0,
			'custom_choice_button_text' => 'Add new choice',
		),
		array(
			'key' => 'field_648341657a01a',
			'label' => 'Fuel economy',
			'name' => 'cmf_fuel_economy',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Fuel economy',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_648341737a01b',
			'label' => 'Vehicle Owner',
			'name' => 'cmf_car_owner',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Car Owner',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_648341817a01c',
			'label' => 'NFT Owner',
			'name' => 'cmf_nft_owner',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'NFT Owner',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_648341907a01d',
			'label' => 'Date Verified',
			'name' => 'cmf_date_verified',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Date Verified',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a196167a1d',
			'label' => 'Number of gears',
			'name' => 'cmf_number_of_gears',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Number of gears',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a196167a1c',
			'label' => 'Top Speed',
			'name' => 'cmf_top_speed',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Top Speed',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a1a1867a1e',
			'label' => 'Steering Wheel',
			'name' => 'cmf_steering_wheel',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Steering Wheel',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a1a3567a1f',
			'label' => 'VAT',
			'name' => 'cmf_vat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'VAT',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a1a4767a20',
			'label' => 'Registered',
			'name' => 'cmf_registered',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Registered',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a1a5867a21',
			'label' => 'Location Country',
			'name' => 'cmf_location_country',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Location Country',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_653a1a6b67a22',
			'label' => 'Number Plate',
			'name' => 'cmf_number_plate',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Number Plate',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_648342dcfec94',
			'label' => 'Is the vehicle titled in your name?',
			'name' => 'cmf_vehicle_titled',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'choices' => array(
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_64834304fec95',
			'label' => 'Do you have the title in hand?',
			'name' => 'cmf_hand_title',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'choices' => array(
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_653924585d707',
			'label' => 'Vehicle Summary',
			'name' => '',
			'aria-label' => '',
			'type' => 'page',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => true,
			'show_numbering' => 0,
			'previous_text' => '',
			'next_text' => '',
		),
		array(
			'key' => 'field_648341e5fec88',
			'label' => 'Vehicle Highlights',
			'name' => 'cmf_vehicle_highlights',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 1,
		),
		array(
			'key' => 'field_64834211fec89',
			'label' => 'Vehicle Equipment',
			'name' => 'cmf_equipment',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 1,
		),
		array(
			'key' => 'field_64834237fec8c',
			'label' => 'Vehicle Modifications',
			'name' => 'cmf_modifications',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 1,
		),
		array(
			'key' => 'field_64834249fec8d',
			'label' => 'Known Issues',
			'name' => 'cmf_known_issues',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 1,
		),
		array(
			'key' => 'field_653924d85d70d',
			'label' => 'Media',
			'name' => '',
			'aria-label' => '',
			'type' => 'page',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => true,
			'show_numbering' => 1,
			'previous_text' => '',
			'next_text' => '',
		),
		array(
			'key' => 'field_6483427dfec90',
			'label' => 'Add Video',
			'name' => 'cmf_videos_re',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Video',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6483428ffec91',
					'label' => 'Video URL',
					'name' => 'cmf_videos',
					'aria-label' => '',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6483427dfec90',
				),
			),
		),
		array(
			'key' => 'field_64834351a2316',
			'label' => 'Exterior Images',
			'name' => 'exterior_images_gallery',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Please upload up to 8 - 10 photos of the exterior of the Vehicle.
Each photo upload must be smaller than 400 kb.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 10,
			'collapsed' => '',
			'button_label' => 'Add Exterior Image',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_654ca4131c7b8',
					'label' => 'Add Image',
					'name' => 'add_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'return_format' => '',
					'library' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_64834351a2316',
				),
			),
		),
		array(
			'key' => 'field_654ca46e1c7b9',
			'label' => 'Interior Images',
			'name' => 'interior_images_gallery',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Please upload up to 8 - 10 photos of the interior of the Vehicle.
Each photo upload must be smaller than 400 kb.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'pagination' => 1,
			'rows_per_page' => 20,
			'min' => 0,
			'max' => 10,
			'collapsed' => '',
			'button_label' => 'Add Interior Image',
			'sub_fields' => array(
				array(
					'key' => 'field_654ca46e1c7ba',
					'label' => 'Add Image',
					'name' => 'add_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'return_format' => '',
					'library' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_654ca46e1c7b9',
				),
			),
		),
		array(
			'key' => 'field_654ca4a41c7bb',
			'label' => 'Mechanical Images',
			'name' => 'mechanical_images_gallery',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Please upload up to 8 - 10 photos of the Mechanical Image of the Vehicle.
Each photo upload must be smaller than 400 kb.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 10,
			'collapsed' => '',
			'button_label' => 'Add Mechanical Image',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_654ca4a41c7bc',
					'label' => 'Add Image',
					'name' => 'add_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'return_format' => '',
					'library' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_654ca4a41c7bb',
				),
			),
		),
		array(
			'key' => 'field_654ca4d41c7bd',
			'label' => 'Docs Images',
			'name' => 'docs_images_gallery',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Please upload up to 8 - 10 photos of the exterior and interior of the Vehicle.
Each photo upload must be smaller than 400 kb.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 10,
			'collapsed' => '',
			'button_label' => 'Add Doc Image',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_654ca4d41c7be',
					'label' => 'Add Image',
					'name' => 'add_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_654ca4d41c7bd',
				),
			),
		),
		array(
			'key' => 'field_654ca69872849',
			'label' => 'Other Images',
			'name' => 'other_images_gallery',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Please upload up to 8 - 10 photos of the exterior and interior of the Vehicle.
Each photo upload must be smaller than 400 kb.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 10,
			'collapsed' => '',
			'button_label' => 'Add Image',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_654ca6987284a',
					'label' => 'Add Image',
					'name' => 'add_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_654ca69872849',
				),
			),
		),
		array(
			'key' => 'field_653924345d706',
			'label' => 'Price',
			'name' => '',
			'aria-label' => '',
			'type' => 'page',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => true,
			'show_numbering' => 0,
			'previous_text' => '',
			'next_text' => '',
		),
		array(
			'key' => 'field_64872d57ff2d1',
			'label' => 'Price',
			'name' => 'woo_ua_opening_price',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64872d7bff2d2',
			'label' => 'Reserve Price',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'message' => 'The reserve price is a pre-set minimum price required for your Vehicle to sell at auction.

For example, if your reserve price is set to $10.00 , you Vehicle will only sell if the highest end bid is at or above $10.00.

Conversely, saying No to a Reserve or setting a No Reserve auction your Vehicle will simply sell to the highest bidder, regardless of the amount.

Selling with a reserve can help protect the seller and ensure they receive a certain minimum price for their Vehicle.

Selling with no reserve can help sellers garner more interest in their Vehicle. In addition, selling without a reserve can help sell the Vehicle for a higher price point due to the increased volume of buyers who prefer to bid on No Reserve auctions.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_64872da5ff2d3',
			'label' => 'Would you like to set a Reserve price for your Vehicle?',
			'name' => 'uwa_auction_has_reserve',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'message' => '',
			'default_value' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_653c9b151cfc5',
			'label' => 'Reserve price',
			'name' => 'woo_ua_lowest_price',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64872da5ff2d3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'af_form',
				'operator' => '==',
				'value' => 'form_6481d7e3e7585',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

