<?php 

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6578622f10def',
	'title' => 'Default Fields For Auction Products',
	'fields' => array(
		array(
			'key' => 'field_65798dff26056',
			'label' => 'Media',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6579a625e61aa',
			'label' => 'Note*',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'red-note',
				'id' => '',
			),
			'message' => 'To hide Gallery field, set the status to \'Disable\' (default: \'Enable\').',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6578628531f26',
			'label' => 'Exterior Images',
			'name' => 'default_exterior_images',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65798f39c5260',
			'label' => 'Interior Images',
			'name' => 'default_interior_images',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65798f49c5261',
			'label' => 'Mechanical Images',
			'name' => 'default_mechanical_images',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65798f57c5262',
			'label' => 'Other Images',
			'name' => 'default_other_images',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65798f67c5263',
			'label' => 'Docs Images',
			'name' => 'default_docs_images',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579b0355c735',
			'label' => 'Videos Gallery',
			'name' => 'default_videos_gallery',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579b0545c736',
			'label' => 'Vehicle History Report',
			'name' => 'default_vehicle_history_report',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657990478446c',
			'label' => 'Vehicle Specification',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6579942c95528',
			'label' => 'Note*',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'red-note',
				'id' => '',
			),
			'message' => 'To hide the Vehicle Information field, set the status to \'Disable\' (default: \'Enable\').',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6579905bd5505',
			'label' => 'Specification Summary',
			'name' => 'default_specification_summary',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579907cd5506',
			'label' => 'Year',
			'name' => 'default_year',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65799096d5508',
			'label' => 'Make',
			'name' => 'default_make',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65799097d5509',
			'label' => 'Model',
			'name' => 'default_model',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c579af6314',
			'label' => 'Location Country',
			'name' => 'default_location_country',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c57a6f6315',
			'label' => 'Location Postal Code',
			'name' => 'default_location_postal_code',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c590152f6b',
			'label' => 'Wheel Size and Type',
			'name' => 'default_wheel_size_and_type',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c57d7f6316',
			'label' => 'Tire Brand and Model',
			'name' => 'default_tire_brand_and_model',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c57f4f6317',
			'label' => 'Tire Size',
			'name' => 'default_tire_size',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c5809f6318',
			'label' => 'Title Status',
			'name' => 'default_title_status',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c5828f6319',
			'label' => 'Name on Title',
			'name' => 'default_name_on_title',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c583df631a',
			'label' => 'State on Title',
			'name' => 'default_state_on_title',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579909ad550b',
			'label' => 'Current mileage on odometer',
			'name' => 'default_mileage',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c593552f6c',
			'label' => 'Is this number accurate?',
			'name' => 'default_is_this_number_accurate',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657c594852f6d',
			'label' => 'Total Miles Accumulated Under Present Ownership?',
			'name' => 'default_total_miles_accumulated_under_present_ownership',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65799099d550a',
			'label' => 'VIN',
			'name' => 'default_vin',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657990bed550d',
			'label' => 'Body Style',
			'name' => 'default_body_style',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657990bfd550e',
			'label' => 'Engine',
			'name' => 'default_engine',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657990c4d550f',
			'label' => 'Drivetrain',
			'name' => 'default_drivetrain',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657990c6d5510',
			'label' => 'Transmission',
			'name' => 'default_transmission',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579916be8457',
			'label' => 'Exterior Color',
			'name' => 'default_exterior_color',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65799179e8459',
			'label' => 'Interior Color',
			'name' => 'default_interior_color',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65799189e845b',
			'label' => 'Condition',
			'name' => 'default_condition',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65799190e845c',
			'label' => 'Registration date',
			'name' => 'default_registration_date',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_65799197e845d',
			'label' => 'Drive Type',
			'name' => 'default_drive_type',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991a1e845e',
			'label' => 'Cylinders',
			'name' => 'default_cylinders',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991a8e845f',
			'label' => 'Doors',
			'name' => 'default_doors',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991afe8460',
			'label' => 'Fuel type',
			'name' => 'default_fuel_type',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991b6e8461',
			'label' => 'Fuel economy',
			'name' => 'default_fuel_economy',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991bce8462',
			'label' => 'Vehicle Owner',
			'name' => 'default_vehicle_owner',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991c3e8463',
			'label' => 'NFT Owner',
			'name' => 'default_nft_owner',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991c9e8464',
			'label' => 'Date Verified',
			'name' => 'default_date_verified',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_657991d1e8465',
			'label' => 'Mileage Reported',
			'name' => 'default_mileage_reported',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579af6df2f77',
			'label' => 'Title Information',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6579af82f2f78',
			'label' => 'Is the vehicle titled in your name?',
			'name' => 'default_is_the_vehicle_titled_in_your_name',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579af9ef2f79',
			'label' => 'Do you have the title in hand?',
			'name' => 'default_do_you_have_the_title_in_hand',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579ae52bed2c',
			'label' => 'Vehicle Details',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6579af4359440',
			'label' => 'Note*',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'red-note',
				'id' => '',
			),
			'message' => 'To hide the Vehicle Information field, set the status to \'Disable\' (default: \'Enable\').',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6579ae6bbed2d',
			'label' => 'Vehicle Highlights',
			'name' => 'default_vehicle_highlights',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579ae78bed2e',
			'label' => 'Vehicle Equipment',
			'name' => 'default_vehicle_equipment',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_658153c658aef',
			'label' => 'Vehicle Modifications',
			'name' => 'default_vehicle_modifications',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_658153f058af0',
			'label' => 'Vehicle Known Issues',
			'name' => 'default_vehicle_known_issues',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_658153f055658af0',
			'label' => 'Vehicle History Report',
			'name' => 'default_vehicle_history_report',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Note: this field only for admin',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
		array(
			'key' => 'field_6579ae88bed2f',
			'label' => 'Dealer Notes',
			'name' => 'default_dealer_notes',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-default-fields',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

